#!/usr/bin/env bash
#


case $1 in

    install)

        cd $HOME/.dotfiles
        stow .
        mkdir $HOME/.local/bin
        cp mt_dotfiles $HOME/.local/bin/mt_dotfiles

        ;;
    update)

        cd $HOME/.dotfiles
        git fetch
        git pull
        stow .

        ;;
esac
